services:

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3338:80"
    pull_policy: always
    environment:
      - BACKEND_URL=https://gs-backend.lestro.top
      - MEILISEARCH_URL=https://gs-meilisearch.lestro.top
      - MEILISEARCH_KEY=masterKey

networks:
  app-network:
    driver: bridge
