services:

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: grandspectra-frontend_solo
    ports:
      - "3339:80"
    environment:
      EXTERNAL_API_URL: "http://localhost:8000"
    pull_policy: always

networks:
  app-network:
    driver: bridge

volumes:
  dbdata:
  laraveldata:
