services:

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3338:80"
    pull_policy: always
    environment:
      - BACKEND_URL=https://gs-backend.lestro.top

networks:
  app-network:
    driver: bridge
